using System.Collections.Generic;

namespace SS_Contacts_API.Models
{
    public class Contact
    {
        public int Id { get; set; } // Autoincremented id is generated by LiteDB
        public Name Name { get; set; }
        public Address Address { get; set; }
        public List<Phone> Phone { get; set; }
        public string Email { get; set; }
    }

    public class Name
    {
        public string First { get; set; }
        public string Middle { get; set; }
        public string Last { get; set; }
    }

    public class Address
    {
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }

    public class Phone
    {
        public string Number { get; set; }
        public string Type { get; set; } // Only accepts "home" | "work" | "mobile"
    }
}